Do not go into the background

diff --git a/.filesystem/bin/Gwall b/.filesystem/bin/Gwall
--- a/.filesystem/bin/Gwall
+++ b/.filesystem/bin/Gwall
@@ -1,42 +1,42 @@
 #!/usr/bin/env bash
 #
-#   vim:ft=sh:fenc=UTF-8:ts=4:sts=4:sw=4:expandtab:foldmethod=marker:foldlevel=0:
+#  vim:ft=sh:fenc=UTF-8:ts=4:sts=4:sw=4:expandtab:foldmethod=marker:foldlevel=0:
 #
-#   $Id: Gwall 954 2008-04-14 16:25:02Z wael $
+#  $Id: Gwall 954 2008-04-14 16:25:02Z wael $
 #
-#   This script will load a random wallpaper on each boot.
-#   Copyright (C) 2006, Wael Nasreddine <wael.nasreddine@gmail.com>
+#  This script will load a random wallpaper on each boot.
+#  Copyright (C) 2006, Wael Nasreddine <wael.nasreddine@gmail.com>
 #
-#   This program is free software; you can redistribute it and/or
-#   modify it under the terms of the GNU General Public License
-#   as published by the Free Software Foundation; either version 2
-#   of the License, or (at your option) any later version.
+#  This program is free software; you can redistribute it and/or
+#  modify it under the terms of the GNU General Public License
+#  as published by the Free Software Foundation; either version 2
+#  of the License, or (at your option) any later version.
 #
-#   This program is distributed in the hope that it will be useful,
-#   but WITHOUT ANY WARRANTY; without even the implied warranty of
-#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
-#   GNU General Public License for more details.
+#  This program is distributed in the hope that it will be useful,
+#  but WITHOUT ANY WARRANTY; without even the implied warranty of
+#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
+#  GNU General Public License for more details.
 #
-#   You should have received a copy of the GNU General Public License
-#   along with this program; if not, write to the Free Software
-#   Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
+#  You should have received a copy of the GNU General Public License
+#  along with this program; if not, write to the Free Software
+#  Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
 #
 
 # Bootstrap{{{
 bootstrap="`dirname $0`/.bootstrap"
 if [ -f "${bootstrap}" ]; then
-    source "${bootstrap}"
+  source "${bootstrap}"
 else
-    echo "Cannot bootstrap"
-    exit 54
+  echo "Cannot bootstrap"
+  exit 54
 fi
 unset bootstrap
 #}}}
 # Source/Create the configurations file.#{{{
 if [ -f ${HOME}/.gwallrc ]; then
-    source ${HOME}/.gwallrc
+  source ${HOME}/.gwallrc
 else
-    cat <<EOF > ${HOME}/.gwallrc
+  cat <<EOF > ${HOME}/.gwallrc
 #
 # Configurations for Gwall.
 #
@@ -60,13 +60,13 @@ else
 # that it is an array so it should look like this example:
 #
 #   FOLDERS=(
-#            \${HOME}/Pictures/Wallpapers/1024x768
-#            \${HOME}/Pictures/Wallpapers/1280x1024
-#            \${HOME}/Pictures/Wallpapers/1280x800
-#            \${HOME}/Pictures/Wallpapers/1600x1200
-#            \${HOME}/Pictures/Wallpapers/800x600
-#            \${HOME}/Pictures/Wallpapers/Other
-#           )
+#      \${HOME}/Pictures/Wallpapers/1024x768
+#      \${HOME}/Pictures/Wallpapers/1280x1024
+#      \${HOME}/Pictures/Wallpapers/1280x800
+#      \${HOME}/Pictures/Wallpapers/1600x1200
+#      \${HOME}/Pictures/Wallpapers/800x600
+#      \${HOME}/Pictures/Wallpapers/Other
+#       )
 #
 # You can disable the image randomizer by setting DISABLE
 # to true, this will disable looking for any wallpaper, and
@@ -94,13 +94,13 @@ ROTATE_SLEEP="900"
 # Folders array
 FOLDERS=( ${HOME}/Pictures/Wallpapers )
 EOF
-    print_error 0 "Please edit ~/.gwallrc and try again."
-    exit 1
+  print_error 0 "Please edit ~/.gwallrc and try again."
+  exit 1
 fi
 #}}}
 # Check if we have Gwall autostart desktop file.#{{{
 if [ ! -f "${HOME}/.config/autostart/Gwall.desktop" ]; then
-    cat << EOF > "${HOME}/.config/autostart/Gwall.desktop"
+  cat << EOF > "${HOME}/.config/autostart/Gwall.desktop"
 
 [Desktop Entry]
 Type=Application
@@ -113,84 +113,80 @@ Comment=Gwall is a background randomiser and rotator.
 Exec=Gwall
 X-GNOME-Autostart-enabled=false
 EOF
-    print_warning 1 "Gwall autostart file has been installed for you in '${HOME}/.config/autostart/Gwall.desktop'\n  It is disabled by default, to enable it please run 'gnome-session-properties'."
+  print_warning 1 "Gwall autostart file has been installed for you in '${HOME}/.config/autostart/Gwall.desktop'\n  It is disabled by default, to enable it please run 'gnome-session-properties'."
 fi
 #}}}
 # If the program is disabled just set the pre-defined wallpaper.#{{{
 if [ ! -z "${DISABLE}" -a "${DISABLE}" = "true" -a "${PROG}" = "feh" ]; then
-    # Setting wallpaper
-    ${PROG} ${ARGS} $(cat ~/.fehbg)
-    exit $?
+  # Setting wallpaper
+  ${PROG} ${ARGS} $(cat ~/.fehbg)
+  exit $?
 elif [ ! -z "${DISABLE}" -a "${DISABLE}" = "true" -a "${PROG}" = "gconftool-2" ]; then
-    # There's no need to set anything up, this is handled by Gnome.
-    exit 0
+  # There's no need to set anything up, this is handled by Gnome.
+  exit 0
 fi
 #}}}
 # Sanity checks#{{{
 if [ -f "${HOME}/.gwall.pid" ]; then
-    OldPID="$( cat "${HOME}/.gwall.pid" )"
-    if ps aux | grep -v grep | awk '{print $2}' | grep -q "${OldPID}"; then
-        print_error 0 "Gwall already running, aborting..."
-        exit 1
-    else
-        rm -f "${HOME}/.gwall.pid"
-    fi
+  OldPID="$( cat "${HOME}/.gwall.pid" )"
+  if ps aux | grep -v grep | awk '{print $2}' | grep -q "${OldPID}"; then
+    print_error 0 "Gwall already running, aborting..."
+    exit 1
+  else
+    rm -f "${HOME}/.gwall.pid"
+  fi
 fi
 if [ ${#FOLDERS[@]} -lt 1 ]; then
-    print_error 0 "Please add folders to FOLDERS array in ~/.gwallrc"
-    exit 1
+  print_error 0 "Please add folders to FOLDERS array in ~/.gwallrc"
+  exit 1
 fi
 for folder in ${FOLDERS[@]}; do
-    [ ! -d "${folder}" ] && \
-        print_warning 0 "The folder '${folder}' does not exist, please review the FOLDERS array in ~/.gwallrc"
+  [ ! -d "${folder}" ] && \
+    print_warning 0 "The folder '${folder}' does not exist, please review the FOLDERS array in ~/.gwallrc"
 done
 if ! type "${PROG}" &>/dev/null ; then
-    print_error 0 "${PROG} is not a valid program"
-    exit 1
+  print_error 0 "${PROG} is not a valid program"
+  exit 1
 fi
 #}}}
 # Build the images array#{{{
 images=()
 for folder in ${FOLDERS[@]}; do
-    # make sure folder does exist
-    [ ! -d "${folder}" ] && \
-        continue
+  # make sure folder does exist
+  [ ! -d "${folder}" ] && \
+    continue
 
-    # make sure path is absolute
-    folder="$(cd ${folder}; pwd)"
+  # make sure path is absolute
+  folder="$(cd ${folder}; pwd)"
 
-    # Build images array
-    images=(${images[*]} $(find ${folder} -mindepth 1 -maxdepth 1 -name *.jpg -o -name *.png -o -name *.gif 2>/dev/null))
+  # Build images array
+  images=(${images[*]} $(find ${folder} -mindepth 1 -maxdepth 1 -name *.jpg -o -name *.png -o -name *.gif 2>/dev/null))
 done
 
 if [ ${#images[@]} -lt 1 ]; then
-    print_error 0 "Folders does not contain any image."
-    exit 1
+  print_error 0 "Folders does not contain any image."
+  exit 1
+fi
+#}}
+# Record the PID#{{{
+# but only if we are rotating..
+if isTrue "${ROTATE}" && isNumber "${ROTATE_SLEEP}"; then
+  echo "$!" > "${HOME}/.gwall.pid"
 fi
 #}}}
 # Set the wallpaper.#{{{
 # If ROTATE is true then rotate the wallpaper while sleeping for ROTATE_SLEEP
-(
-    while true; do
+while true; do
+  # Generating a random number between 0 and ${#images[@]}
+  rand="$(expr $RANDOM % ${#images[@]})"
 
-        # Generating a random number between 0 and ${#images[@]}
-        rand="$(expr $RANDOM % ${#images[@]})"
-
-        # Setting wallpaper
-        ${PROG} ${ARGS} ${images[$rand]}
-        if isTrue "${ROTATE}" && isNumber "${ROTATE_SLEEP}"; then
-            sleep "${ROTATE_SLEEP}"
-            continue
-        else
-            break
-        fi
-    done
-) &
-NewPID="$!"
-#}}}
-# Record the PID#{{{
-# but only if we are rotating..
-if isTrue "${ROTATE}" && isNumber "${ROTATE_SLEEP}"; then
-    echo "${NewPID}" > "${HOME}/.gwall.pid"
-fi
+  # Setting wallpaper
+  ${PROG} ${ARGS} ${images[$rand]}
+  if isTrue "${ROTATE}" && isNumber "${ROTATE_SLEEP}"; then
+    sleep "${ROTATE_SLEEP}"
+    continue
+  else
+    break
+  fi
+done
 #}}}
