Allow for several keyboard layouts (#222)
* [modules/{nixos,home}/keyboard] allow for several different keyboard layouts

* hosts: use new keyboard configuration

* [modules/home/software] use new keyboard configuration

* [modules/home/software/neovim] use new keyboard configuration

* copy the keyboard module over from home

* fix all calls

* fix formatting

* fix the build finally

* fix the build

* enable at boot by default

* fix zeus

* merge lesskey into the default as a string

* make it work again

* fix a typo

* do not attempt cachix push if the key is not available (case of a fork)

* add a note

* [modules/home/software/less] add bépo keybindings

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -54,6 +54,13 @@ var_5: &push-to-cachix
         source "${HOME}/.nix-profile/etc/profile.d/nix.sh"
       fi
 
+      # The CACHIX_SIGNING_KEY is not available for pull requests coming from a
+      # fork for security reasons.
+      if [[ -z "${CACHIX_SIGNING_KEY:-}" ]]; then
+        >&2 echo "CACHIX_SIGNING_KEY is not set, cannot push to cachix"
+        exit 0
+      fi
+
       ./scripts/push-to-cachix.sh "${CIRCLE_JOB}"
 
 version: 2
