CircleCI: use the shabka-yl context
This context exports the following keys:
- CACHIX_CACHE
- CACHIX_SIGNING_KEY

Both keys are required!

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -1,5 +1,4 @@
 var_0: &global_env
-  CACHIX_CACHE: yl
 
 var_1: &install-nix
   run:
@@ -56,10 +55,13 @@ var_5: &push-to-cachix
         source "${HOME}/.nix-profile/etc/profile.d/nix.sh"
       fi
 
-      # The CACHIX_SIGNING_KEY is not available for pull requests coming from a
-      # fork for security reasons.
+      # Cachix is not available for pull requests coming from a fork for security reasons.
       if [[ -z "${CACHIX_SIGNING_KEY:-}" ]]; then
         >&2 echo "CACHIX_SIGNING_KEY is not set, cannot push to cachix"
+        exit 0
+      fi
+      if [[ -z "${CACHIX_CACHE:-}" ]]; then
+        >&2 echo "CACHIX_CACHE is not set, cannot push to cachix"
         exit 0
       fi
 
@@ -190,14 +192,14 @@ workflows:
   testing:
     jobs:
       - athena:
-          context: nix-global
+          context: shabka-yl
       - cratos:
-          context: nix-global
+          context: shabka-yl
       - hades:
-          context: nix-global
+          context: shabka-yl
       - hera:
-          context: nix-global
+          context: shabka-yl
       - poseidon:
-          context: nix-global
+          context: shabka-yl
       - zeus:
-          context: nix-global
+          context: shabka-yl
