fix more scripts

diff --git a/.bin/cs b/.bin/cs
--- a/.bin/cs
+++ b/.bin/cs
@@ -1,56 +1,56 @@
 #!/usr/bin/env bash
 #
-#   vim:ft=sh:fenc=UTF-8:ts=4:sts=4:sw=4:expandtab:foldmethod=marker:foldlevel=0:
+# vim:foldmethod=marker:foldlevel=0:
 #
-#   $Id: cs 789 2008-03-24 13:02:06Z wael $
+# Copyright (c) 2014-2017 Wael Nasreddine <wael.nasreddine@gmail.com>
 #
-#   Copyright (c) 2007 Wael Nasreddine <wael.nasreddine@gmail.com>
+# Permission is hereby granted, free of charge, to any person obtaining a copy
+# of this software and associated documentation files (the "Software"), to deal
+# in the Software without restriction, including without limitation the rights
+# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
+# copies of the Software, and to permit persons to whom the Software is
+# furnished to do so, subject to the following conditions:
 #
-#   This program is free software; you can redistribute it and/or modify
-#   it under the terms of the GNU General Public License as published by
-#   the Free Software Foundation; either version 2 of the License, or
-#   (at your option) any later version.
+# The above copyright notice and this permission notice shall be included in
+# all copies or substantial portions of the Software.
 #
-#   This program is distributed in the hope that it will be useful,
-#   but WITHOUT ANY WARRANTY; without even the implied warranty of
-#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
-#   GNU General Public License for more details.
+# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
+# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
+# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
+# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
+# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
+# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
+# SOFTWARE.
 #
-#   You should have received a copy of the GNU General Public License
-#   along with this program; if not, write to the Free Software
-#   Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA 02111-1307,
-#   USA.
-#
-
-set -e
 
 # Bootstrap{{{
 bootstrap="$( dirname "${0}" )/.bootstrap"
 if [ -f "${bootstrap}" ]; then
-    # shellcheck disable=1090
-    source "${bootstrap}"
+  # shellcheck disable=1090
+  source "${bootstrap}"
 else
-    echo "Cannot bootstrap"
-    exit 54
+  echo "Cannot bootstrap"
+  exit 54
 fi
 unset bootstrap
 #}}}
-
+# Main {{{
 start_editor="true"
 if [[ "${1}" = "--no-editor" ]]; then
-    start_editor="false"
-    shift
+  start_editor="false"
+  shift
 fi
 
 if [ "${#}" -ne "1" ]; then
-    print_error 0 "Usage: ${0} [--no-editor] <script_name>"
-    exit 1
+  print_error 0 "Usage: ${0} [--no-editor] <script_name>"
+  exit 1
 fi
 
-cd "$( dirname "${0}" )"
-if [ ! -f "${1}" ]; then
-    cp .tmpl "${1}"
-    chmod +x "${1}"
+cd "$( dirname "${0}" )" || exit 1
+if [[ ! -f "${1}" ]]; then
+  cp .tmpl "${1}"
+  chmod +x "${1}"
 fi
 
 [[ "${start_editor}" = "true" ]] && $EDITOR "${1}"
+# }}}
diff --git a/.bin/gpg-clean-up b/.bin/gpg-clean-up
--- a/.bin/gpg-clean-up
+++ b/.bin/gpg-clean-up
@@ -1,9 +1,8 @@
 #!/usr/bin/bash
 set -e
 
-#
-# Credit to [Warren
-# Lavallee](https://superuser.com/users/403968/warren-lavallee) for this script
+
+# Credit to [Warren Lavallee](https://superuser.com/users/403968/warren-lavallee) for this script
 # https://superuser.com/questions/594116/clean-up-my-gnupg-keyring/859739#859739
 
 #
@@ -12,31 +11,29 @@ set -e
 
 echo -n "Expired Keys: "
 for expiredKey in $(gpg2 --list-keys | awk '/^pub.* \[expired\: / {id=$2; sub(/^.*\//, "", id); print id}' | fmt -w 999 ); do
-    echo -n "$expiredKey"
-    gpg2 --batch --quiet --delete-keys $expiredKey >/dev/null 2>&1
-    if [ $? -eq 0 ]; then
-        echo -n "(OK), "
-    else
-        echo -n "(FAIL), "
-    fi
+  echo -n "$expiredKey"
+  gpg2 --batch --quiet --delete-keys "$expiredKey" >/dev/null 2>&1
+  if [ $? -eq 0 ]; then
+    echo -n "(OK), "
+  else
+    echo -n "(FAIL), "
+  fi
 done
 echo done.
 
 echo -n "Update Keys: "
 for keyid in $(gpg -k | grep ^pub | grep -v expired: | grep -v revoked: | cut -d/ -f2 | cut -d' ' -f1); do
-    echo -n "$keyid"
-    gpg2 --batch --quiet --edit-key "$keyid" check clean cross-certify save quit > /dev/null 2>&1
-    if [ $? -eq 0 ]; then
-        echo -n "(OK), "
-    else
-        echo -n "(FAIL), "
-    fi
+  echo -n "$keyid"
+  if gpg2 --batch --quiet --edit-key "$keyid" check clean cross-certify save quit > /dev/null 2>&1; then
+    echo -n "(OK), "
+  else
+    echo -n "(FAIL), "
+  fi
 done
 echo done.
 
-gpg2 --batch --quiet --refresh-keys > /dev/null 2>&1
-if [ $? -eq 0 ]; then
-    echo "Refresh OK"
+if gpg2 --batch --quiet --refresh-keys > /dev/null 2>&1; then
+  echo "Refresh OK"
 else
-     echo "Refresh FAIL."
+  echo "Refresh FAIL."
 fi
