Makefile: kill bootstrap.sh in favor of Makefile tasks

diff --git a/lib/shell/bin/nixos-rebuild b/lib/shell/bin/nixos-rebuild
--- a/lib/shell/bin/nixos-rebuild
+++ b/lib/shell/bin/nixos-rebuild
@@ -1,32 +1,38 @@
 #!/usr/bin/env bash
 
+# NOTE: this script should not use nix-shell
+
 set -euo pipefail
 
-if [[ "${#}" -lt 1 ]]; then
-	echo "USAGE: sudo ./scripts/bootstrap.sh <machine>"
+if [[ "${#}" -lt 2 ]]; then
+	echo "USAGE: ${BASH_SOURCE[0]} <machine> <action>"
 	echo "ERR: You must provide a host to bootstrap, <machine> must exist under nixos/machines/"
 	exit 1
 fi
 
-readonly here="$(cd $(dirname "${BASH_SOURCE[0]}")/.. && pwd)"
+readonly here="$(cd $(dirname "${BASH_SOURCE[0]}")/../../.. && pwd)"
 readonly machine="${1}"
+	readonly action="${2}"
 
 if [[ ! -r "${here}/nixos/machines/${machine}/configuration.nix" ]]; then
 	echo "ERR: configuration for machine ${machine} does not exist."
 	exit 1
 fi
 
-if [[ "${#}" -eq 2 ]]; then
-	readonly action="${2}"
+if [[ "${action}" == "test" ]] || [[ "${action}" == "switch" ]]; then
+	readonly HOSTNAME="$(hostname -s)"
+	if [[ "${machine}" != "${HOSTNAME}" ]]; then
+		echo "ERR: cannot run \'nixos-rebuild ${action}\` for ${machine} from ${HOSTNAME}."
+		exit 1
+	fi
 fi
 
-if [[ $(id -u) -gt 0 ]]; then
+if [[ "${action}" == "switch" ]] && [[ $(id -u) -gt 0 ]]; then
 	echo -e "must run this as root"
 	exit 1
 fi
 
-NIX_PATH=""
-NIX_PATH="${NIX_PATH}:home-manager=${here}/external/home-manager"
+NIX_PATH="home-manager=${here}/external/home-manager"
 NIX_PATH="${NIX_PATH}:nixos-config=${here}/nixos/machines/${machine}/configuration.nix"
 NIX_PATH="${NIX_PATH}:nixos-hardware=${here}/external/nixos-hardware"
 NIX_PATH="${NIX_PATH}:nixpkgs-overlays=${here}/overlays"
@@ -34,5 +40,4 @@ NIX_PATH="${NIX_PATH}:nixpkgs=${here}/external/nixpkgs"
 NIX_PATH="${NIX_PATH}:system-path=${here}"
 export NIX_PATH
 
-echo "NIX_PATH=$NIX_PATH"
-nixos-rebuild "${action:-switch}"
+nixos-rebuild "${action}"
